### PR TITLE
Education Content

### PR DESCRIPTION
**Pull request by shawnmclean**
Related to Issue #3.

Definition of Done:

- [x] Link back to Manifestos page.
- [x] 1
- [x] 2
- [x] 4
- [x] 5
- [x] 12
- [x] 13
- [x] 17
- [x] 18
- [x] 19
- [x] 20
- [x] Nav Tabs

### CODE REVIEW

**Comment by marcamillion** [comment]
How this stay @shawnmclean? We need to get this site finished so the JLP can push it.

**Comment by shawnmclean** [comment]
In a few minutes.

**Comment by marcamillion** [comment]
Ok.... @djuvane or @luechenchris will work on the navigation tomorrow. So for now, what we should do is just add the content, but comment out the links in the navigation. We don't want the PR team over at the JLP to review the site, see the menu is broken and assume it isn't ready. So as we add content, we just add the pill but comment it. Once Djuvane or Luchen look at it, they will fix the menu and uncomment it.

**Comment by shawnmclean** [comment]
@marcamillion ready for review and merge.

**Comment by marcamillion** [comment]
Looks good @shawnmclean. Thanks!

**Comment by marcamillion** [comment]
Dammit @shawnmclean, my bad. One thing I missed. The Footer. I had updated the footer on all the pages, I believe before you forked your local branch. Can you update this `/education.html` with the correct footer - which you can get from any of the other pages please.

Thanks.

**Pull request merged**
